### ISSUE TITLE
Mac白色模式下选择文本无背景颜色

### ISSUE THREAD

**Issue by sunjianan9900** [coolpace/V2EX_Polish#16]
截图1我是已经选择了URL，而且可以正常复制，但是完全看不出来选择：
![image](https://user-images.githubusercontent.com/10936316/236377712-a6739927-9ff2-4c2a-bd9c-e6ed3f9e4efc.png)
另附上其他网站正常选择的效果：
![image](https://user-images.githubusercontent.com/10936316/236377752-c347e11c-5836-462d-9fa0-9376da7d2e50.png)

**Comment by sunjianan9900** [comment]
浏览器是 EDGE

**Comment by Codennnn** [comment]
@Codennnn

**Comment by Codennnn** [comment]
在深色模式下是否也有该问题？

**Comment by sunjianan9900** [comment]
> 在深色模式下是否也有该问题？

也是一样的，没有选择背景色。
关闭插件原站正常

**Comment by sunjianan9900** [comment]
刚刚测试了一下，系统 黑/白 和 插件 黑/白 分别排列组合4种，都是看不到选择颜色

**Comment by sunjianan9900** [comment]
系统 MacOS 13.3.1

**Comment by Codennnn** [comment]
这就有点奇怪了，之前从未有人报告过这个问题，所以我认为这是个例，晚点我调试一下

**Comment by Codennnn** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/47730755/236486904-4e7101a2-68c0-477e-865b-7c65e9cf0d00.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/47730755/236486995-b43da57b-048b-4db8-8bc8-0ca42c1d14f3.png">

我在 MacOS 13.3.1 Edge 下的显示效果是正常的，你是否有设置自己的自定义 CSS 呢？

**Comment by sunjianan9900** [comment]
我测试了一下，Chrome是没有问题的
但是Edge就是不行，关闭所有插件仅剩这个也不行，新建一个用户配置窗口，从零开始只安装这个插件也不行。v2本身可以滑动选择有背景色，启用本插件就会导致无背景色问题

**Comment by sunjianan9900** [comment]
> 我测试了一下，Chrome是没有问题的 但是Edge就是不行，关闭所有插件仅剩这个也不行，新建一个用户配置窗口，从零开始只安装这个插件也不行。v2本身可以滑动选择有背景色，启用本插件就会导致无背景色问题

![image](https://user-images.githubusercontent.com/10936316/236491574-ba71f5f4-420c-45ac-9850-ac7dfde30378.png)

版本 112.0.1722.68 (正式版本) (arm64)

**Comment by Codennnn** [comment]
在[设置页 ](https://www.v2ex.com/settings)添加如下 CSS，看看是否有效果？

```css
:root body ::selection {
background-color: blue;
}
```

<img width="463" alt="image" src="https://user-images.githubusercontent.com/47730755/236505031-71d95f4a-5d1a-40cd-957a-81b0f684f3c2.png">

**Comment by Codennnn** [comment]
另外，也请确保你在 Edge 安装的 V2EX Polish 是正确的版本，最新版为 1.3.4

**Comment by sunjianan9900** [comment]
> 在[设置页 ](https://www.v2ex.com/settings)添加如下 CSS，看看是否有效果？
> 
> ```css
> :root body ::selection {
> background-color: blue;
> }
> ```
> 
> <img alt="image" width="463" src="https://user-images.githubusercontent.com/47730755/236505031-71d95f4a-5d1a-40cd-957a-81b0f684f3c2.png">

按照你说的自定义css生效了，之前都不知道还有这个设置。感谢

![image](https://user-images.githubusercontent.com/10936316/236589256-1c4d84ae-7e0a-4a98-81bf-6d7e009620bc.png)

另外是最新版本 1.3.4（从chrome商店下载的）

**Comment by Codennnn** [comment]
好的，但我还不清楚是什么原因造成插件的 CSS 失效，在找到问题之前，请你在自定义 CSS 中插入以下代码来修复：

```css
:root body ::selection {
  color: var(--v2p-color-main-100);
  background-color: var(--v2p-color-main-700);
}

:root body img::selection {
  background-color: var(--v2p-color-main-500);
}

:root body:has(#Wrapper.Night) ::selection {
  color: var(--v2p-color-background);
  background-color: var(--v2p-color-foreground);
}

:root body:has(#Wrapper.Night) img::selection {
  background-color: var(--v2p-color-foreground);
}
```
