### ISSUE TITLE
多行超链接hover时下划线显示不全

### ISSUE THREAD

**Issue by sortbylist** [coolpace/V2EX_Polish#25]
右侧今日热议主题，鼠标移到文字上，如果文字为多行时，第二行文字的下划线没有显示

官方效果
![image](https://github.com/coolpace/V2EX_Polish/assets/2787404/e493a084-bf29-4b3c-93d2-a7e0c65c9092)

启用插件效果
![image](https://github.com/coolpace/V2EX_Polish/assets/2787404/630999df-7e32-4c4f-a4b4-fffb8c536862)

**Comment by Codennnn** [comment]
我分别在 Chrome、Edge、Firefox 上查看了，均未发现此问题。检查下有没有可能你使用了 V2EX Polish 以外的插件，影响了样式。
![image](https://github.com/coolpace/V2EX_Polish/assets/47730755/be1185ed-9b18-4f2c-99f3-9cb9ab3cd4c4)

**Comment by sortbylist** [comment]
@Codennnn 你看下今天的热议主题，多看几个标题，有的显示正常，有的不正常。我用chrome开启隐身模式，只启用V2EX Polish 插件试了，还是存在这个问题。

**Comment by sortbylist** [comment]
edge隐身模式，只启用v2ex polish插件，显示正常。
chrome隐身模式，只启用v2ex polish插件，显示不正常。chrome版本号：版本 113.0.5672.127（正式版本） （32 位）

**Comment by sortbylist** [comment]
![image](https://github.com/coolpace/V2EX_Polish/assets/2787404/589dc54f-7f23-4d4a-aace-7166ece1e5e2)

**Comment by Codennnn** [comment]
我这真的看到是正常的，目前只有你报告了这个问题，要不你打开控制台调下样式找找原因？

**Comment by sortbylist** [comment]
@Codennnn 对前端不熟，我用F12定位到是`body .item_hot_topic_title` 这个元素的CSS有问题，将`overflow:hidden;`改成`overflow:initial;`，可以解决。不知道改完会不会有别的影响。

```css
body .item_hot_topic_title {
	display:-webkit-box;
	overflow:initial;
	-webkit-box-orient:vertical;
	-webkit-line-clamp:2;
	line-height:1.4;
	text-shadow:none
}

```

另外在firefox上也复现出这个问题了，firefox版本：113.0.2 (64 位)，v2ex polish 插件版本：1.4.11。
