### ISSUE TITLE
首页搜索框内容被导航遮挡

### ISSUE THREAD

**Issue by diluy** [coolpace/V2EX_Polish#7]
![screenshot-20230412-180204](https://user-images.githubusercontent.com/3415206/231428655-56acc882-893f-49b9-a489-1eaee934382d.png)

**Comment by Codennnn** [comment]
这个样式问题会在下次更新中修复，目前可以先使用[自定义样式](https://www.v2ex.com/settings)来进行调整：

```css
body #search-container #search-result {
  z-index: 99;
}
```

![image.png](https://volta.s3.fr-par.scw.cloud/image_b331902c1c.png)
